//
//  NewsListRouter.swift
//  NewsDemo
//
//  Created by Jasper Alain Goce on 26/09/2019.
//  Copyright (c) 2019 blessed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsListRoutingLogic
{
    func navigateToSomewhere(source: NewsListViewController, destination: UIViewController)
}

protocol NewsListDataPassing
{
    var dataStore: NewsListDataStore? { get }
}

class NewsListRouter: NSObject, NewsListRoutingLogic, NewsListDataPassing
{
    weak var viewController: NewsListViewController?
    var dataStore: NewsListDataStore?
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: NewsListViewController, destination: UIViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: NewsListDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
