//
//  NewsListWorker.swift
//  NewsDemo
//
//  Created by Jasper Alain Goce on 26/09/2019.
//  Copyright (c) 2019 blessed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol NewsListStoreProtocol: class
{
    func getNews(parameter: NewsList.Request.NewsRequest, completion: @escaping(NewsList.Response.NewsResponse?) -> Void)
}

class NewsListWorker
{
    var newsListStore: NewsListStoreProtocol
    
    init(newsListStore: NewsListStoreProtocol)
    {
        self.newsListStore = newsListStore
    }
    
    func getNews(parameter: NewsList.Request.NewsRequest, completion: @escaping(NewsList.Response.NewsResponse?) -> Void)
    {
        newsListStore.getNews(parameter: parameter) { newsRes in
            completion(newsRes)
        }
    }
}
