//
//  NewsListPresenter.swift
//  NewsDemo
//
//  Created by Jasper Alain Goce on 26/09/2019.
//  Copyright (c) 2019 blessed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListPresentationLogic
{
    func presentNews(response: NewsList.Response.NewsResponse?)
}

class NewsListPresenter: NewsListPresentationLogic
{
    weak var viewController: NewsListDisplayLogic?
    
    func presentNews(response: NewsList.Response.NewsResponse?)
    {
        if response?.responses.count != 0 {
            if let cards = response?.responses.first?.cards {
                let viewModel = NewsList.ViewModel(dataSource: cards)
                viewController?.displayNews(viewModel: viewModel)
            } else {
                viewController?.displayError(errMsg: "No news available")
            }
        } else {
            viewController?.displayError(errMsg: "No response")
        }
    }
}
