//
//  NewsListInteractor.swift
//  NewsDemo
//
//  Created by Jasper Alain Goce on 26/09/2019.
//  Copyright (c) 2019 blessed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsListBusinessLogic
{
    func getNews(requestParam: NewsList.Request.NewsRequest)
}

protocol NewsListDataStore
{
    
}

class NewsListInteractor: NewsListBusinessLogic, NewsListDataStore
{
    var presenter: NewsListPresentationLogic?
    var worker: NewsListWorker?
    
    func getNews(requestParam: NewsList.Request.NewsRequest)
    {
        worker = NewsListWorker(newsListStore: NewsListAPIStore())
        worker?.getNews(parameter: requestParam, completion: { [weak self] (newsRes) in
            debugPrint(newsRes)
            self?.presenter?.presentNews(response: newsRes)
        })
    }
}
